#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_jet_tx1_2() {
    echo 1
}

SystemName_jet_tx1_2() {
    echo "jet_tx1_2"
}

SystemPowerOff_jet_tx1_2() {
    RebootShutdown jetson-tx1-2
}

Arch_jet_tx1_2() {
    echo "arm"
}

ISA_jet_tx1_2() {
    echo "armv8-a"
}

SOC_jet_tx1_2() {
    echo "TegraTX1"
}

CPU_jet_tx1_2() {
    echo "cortex-a57"
}

Cores_jet_tx1_2() {
    echo "4"
}

RAM_jet_tx1_2() {
    echo "4GB"
}

MaxCLK_jet_tx1_2() {
    echo "1.9Ghz"
}

Sel4Plat_jet_tx1_2() {
    echo "tx1"
}
