#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_jetson() {
    echo 1
}

SystemName_jetson() {
    echo "jetson1"
}

SystemPowerOff_jetson() {
    RebootShutdown jetson1
}

Arch_jetson() {
    echo "arm"
}

ISA_jetson() {
    echo "armv7-a"
}

SOC_jetson() {
    echo "TegraK1"
}

CPU_jetson() {
    echo "cortex-a15"
}

Cores_jetson() {
echo "4(1)"
}

RAM_jetson() {
    echo "2GB"
}

MaxCLK_jetson() {
    echo "2.3Ghz"
}

Sel4Plat_jetson() {
    echo "tk1"
}
