#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_jetson4() {
    echo 1
}

SystemName_jetson4() {
    echo "jetson4"
}

SystemPowerOff_jetson4() {
    RebootShutdown jetson4
}

Arch_jetson4() {
    echo "arm"
}

ISA_jetson4() {
    echo "armv7-a"
}

SOC_jetson4() {
    echo "TegraK1"
}

CPU_jetson4() {
    echo "cortex-a15"
}

Cores_jetson4() {
    echo "4(1)"
}

RAM_jetson4() {
    echo "2GB"
}

MaxCLK_jetson4() {
    echo "2.3Ghz"
}

Sel4Plat_jetson4() {
    echo "tk1"
}
