#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_kzm() {
    echo 1
}

SystemName_kzm() {
    echo "kzm11"
}

SystemPowerOff_kzm() {
    RebootShutdown kzm
}

Arch_kzm() {
    echo "arm"
}

ISA_kzm() {
    echo "armv6"
}

SOC_kzm() {
    echo "imx31"
}

CPU_kzm() {
    echo "arm1136"
}

Cores_kzm() {
    echo "1"
}

RAM_kzm() {
    echo "128MB"
}

MaxCLK_kzm() {
    echo "532Mhz"
}

Sel4Plat_kzm() {
    echo "imx31:kzm"
}
