#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_odroidxu() {
    echo 1
}

function SystemName_odroidxu() {
    echo "odroid-xu"
}

function SystemPowerOff_odroidxu() {
    RebootShutdown odroid-xu
}

function Arch_odroidxu() {
    echo "arm"
}

function ISA_odroidxu() {
    echo "armv7-a"
}

function SOC_odroidxu() {
    echo "exynos5410"
}

function CPU_odroidxu() {
    echo "cortex-a15(a7)"
}

function Cores_odroidxu() {
    echo "4(8)"
}

function RAM_odroidxu() {
    echo "2GB"
}

function MaxCLK_odroidxu() {
    echo "2Ghz"
}

function Sel4Plat_odroidxu() {
    echo "exynos5:exynos5410"
}
