#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_odroidc2() {
    echo 1
}

SystemName_odroidc2() {
    echo "odroidc2"
}

SystemPowerOff_odroidc2() {
    RebootShutdown odroidc2
}

Arch_odroidc2() {
    echo "arm"
}

ISA_odroidc2() {
    echo "armv8-a"
}

SOC_odroidc2() {
    echo "odroidc2"
}

CPU_odroidc2() {
    echo "cortex-a53"
}

Cores_odroidc2() {
    echo "4"
}

RAM_odroidc2() {
    echo "2GB"
}

MaxCLK_odroidc2() {
    echo "1.5GHz"
}

Sel4Plat_odroidc2() {
    echo "odroidc2"
}
