#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_odroidxu() {
    echo 1
}

SystemName_odroidxu() {
    echo "odroid-xu"
}

SystemPowerOff_odroidxu() {
    RebootShutdown odroid-xu
}

Arch_odroidxu() {
    echo "arm"
}

ISA_odroidxu() {
    echo "armv7-a"
}

SOC_odroidxu() {
    echo "exynos5410"
}

CPU_odroidxu() {
    echo "cortex-a15(a7)"
}

Cores_odroidxu() {
    echo "4(8)"
}

RAM_odroidxu() {
    echo "2GB"
}

MaxCLK_odroidxu() {
    echo "2Ghz"
}

Sel4Plat_odroidxu() {
    echo "exynos5:exynos5410"
}
