#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_odroid() {
    echo 1
}

SystemName_odroid() {
    echo "odroid"
}

SystemPowerOff_odroid() {
    RebootShutdown odroid
}

Arch_odroid() {
    echo "arm"
}

ISA_odroid() {
    echo "armv7-a"
}

SOC_odroid() {
    echo "exynos4412"
}

CPU_odroid() {
    echo "cortex-a9"
}

Cores_odroid() {
    echo "4"
}

RAM_odroid() {
    echo "1GB"
}

MaxCLK_odroid() {
    echo "1.4Ghz"
}

Sel4Plat_odroid() {
    echo "exynos4"
}
