#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_rockpro64a() {
    echo 1
}

SystemName_rockpro64a() {
    echo "rockpro64a"
}

SystemPowerOff_rockpro64a() {
    RebootShutdown rockpro64a
}

Arch_rockpro64a() {
    echo "arm"
}

ISA_rockpro64a() {
    echo "armv8-a"
}

SOC_rockpro64a() {
    echo "Rockchip RK3399"
}

CPU_rockpro64a() {
    echo "cortex-a53/a72"
}

Cores_rockpro64a() {
    echo "4+2"
}

RAM_rockpro64a() {
    echo "4GB"
}

MaxCLK_rockpro64a() {
    echo "1.9Ghz"
}

Sel4Plat_rockpro64a() {
    echo "rockpro64"
}

PXELinux_rockpro64a() {
    echo "no"
}

DTB_rockpro64a() {
    echo "no"
}
