#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_rpi3() {
    echo 1
}

SystemName_rpi3() {
    echo "rpi3"
}

SystemPowerOff_rpi3() {
    RebootShutdown rpi3
}

Arch_rpi3() {
    echo "arm"
}

ISA_rpi3() {
    echo "armv8-a"
}

SOC_rpi3() {
    echo "bcm2837"
}

CPU_rpi3() {
    echo "cortex-a53"
}

Cores_rpi3() {
    echo "4"
}

RAM_rpi3() {
    echo "1GB"
}

MaxCLK_rpi3() {
    echo "1.2Ghz"
}

Sel4Plat_rpi3() {
    echo "bcm2837:rpi3"
}
