#!/bin/bash
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sandy() {
    echo 2
}

function SystemName_sandy() {
    echo "sandy"
}

function SystemPowerOff_sandy() {
    RebootShutdown sandy
}

function Arch_sandy() {
    echo "x86"
}

function ISA_sandy() {
    echo "x86_64"
}

function SOC_sandy() {
    echo "sandybridge"
}

function CPU_sandy() {
    echo "i7-2600"
}

function Cores_sandy() {
    echo "4"
}

function RAM_sandy() {
    echo "?"
}

function MaxCLK_sandy() {
    echo "3.4Ghz"
}

function Sel4Plat_sandy() {
    echo "pc99:sandybridge"
}
