#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_skylake4() {
    echo 2
}

SystemName_skylake4() {
    echo "skylake4"
}

SystemPowerOff_skylake4() {
    RebootShutdown skylake4
}

Arch_skylake4() {
    echo "x86"
}

ISA_skylake4() {
    echo "x86_64"
}

SOC_skylake4() {
    echo "skylake4"
}

CPU_skylake4() {
    echo "i7-6700"
}

Cores_skylake4() {
    echo "4"
}

RAM_skylake4() {
    echo "8GB"
}

MaxCLK_skylake4() {
    echo "3.4Ghz"
}

Sel4Plat_skylake4() {
    echo "pc99:skylake"
}
