#!/bin/bash
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_tardec1() {
    echo 2
}

function SystemName_tardec1() {
    echo "tardec1"
}

function SystemPowerOff_tardec1() {
    RebootShutdown tardec1
}

function Arch_tardec1() {
    echo "x86"
}

function ISA_tardec1() {
    echo "x86_64"
}

function SOC_tardec1() {
    echo "?"
}

function CPU_tardec1() {
    echo "i7-351UE"
}

function Cores_tardec1() {
    echo "2"
}

function RAM_tardec1() {
    echo "4GB"
}

function MaxCLK_tardec1() {
    echo "1.7Ghz"
}

function Sel4Plat_tardec1() {
    echo "pc99"
}
