#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_tx2() {
    echo 1
}

function SystemName_tx2() {
    echo "tx2"
}

function SystemPowerOff_tx2() {
    RebootShutdown tx2
}

function Arch_tx2() {
    echo "arm"
}

function ISA_tx2() {
    echo "armv8-a"
}

function SOC_tx2() {
    echo "TegraTX2"
}

function CPU_tx2() {
    echo "cortex-a57"
}

function Cores_tx2() {
    echo "4"
}

function RAM_tx2() {
    echo "8GB"
}

function MaxCLK_tx2() {
    echo "1.9Ghz"
}

function Sel4Plat_tx2() {
    echo "tx2"
}
