#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_zc706() {
    echo 1
}

SystemName_zc706() {
    echo "zc706"
}

SystemPowerOff_zc706() {
    RebootShutdown zc706
}

Arch_zc706() {
    echo "arm"
}

ISA_zc706() {
    echo "armv7-a"
}

SOC_zc706() {
    echo "zynq-7000"
}

CPU_zc706() {
    echo "cortex-a9"
}

Cores_zc706() {
    echo "2"
}

RAM_zc706() {
    echo "1GB"
}

MaxCLK_zc706() {
    echo "800Mhz"
}

Sel4Plat_zc706() {
    echo "zynq7000"
}
