#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_bboneblack() {
    echo 1
}

SystemName_bboneblack() {
    echo "bboneblack"
}

SystemPowerOff_bboneblack() {
    RebootShutdown bboneblack
}

Arch_bboneblack() {
    echo "arm"
}

ISA_bboneblack() {
    echo "armv7"
}

SOC_bboneblack() {
    echo "am335x"
}

CPU_bboneblack() {
    echo "cortex-a8"
}

Cores_bboneblack() {
    echo "1"
}

RAM_bboneblack() {
    echo "512MB"
}

MaxCLK_bboneblack() {
    echo "1GHZ"
}

Sel4Plat_bboneblack() {
    echo "am335x:am335x-boneblack"
}
