#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_beagle() {
    echo 1
}

function SystemRunImage_beagle() {
    local completion=$1
    local completion_timeout=$2
    local output=$3
    local kernel=$4
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${output}" "${kernel}" beagle1
    return $?
}

function SystemPowerOff_beagle() {
    RebootShutdown beagle
}

function Arch_beagle() {
    echo "arm"
}

function ISA_beagle() {
    echo "armv7-a"
}

function SOC_beagle() {
    echo "omap3"
}

function CPU_beagle() {
    echo "cortex-a9"
}

function Cores_beagle() {
    echo "1"
}

function RAM_beagle() {
    echo "256MB"
}

function MaxCLK_beagle() {
    echo "720Mhz"
}

