#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_boost() {
    echo 2
}

function SystemRunImage_boost() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    local rootserver=$6
    RebootConsoleRunTwoFiles "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" "${rootserver}" boost
    return $?
}

function SystemPowerOff_boost() {
    RebootShutdown boost
}

function Arch_boost() {
    echo "x86"
}

function ISA_boost() {
    echo "x86_64"
}

function SOC_boost() {
    echo "xeon"
}

function CPU_boost() {
    echo "?"
}

function Cores_boost() {
    echo "4"
}

function RAM_boost() {
    echo "?"
}

function MaxCLK_boost() {
    echo "?"
}