#!/bin/sh
#
# Copyright 2025 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_cheshire1() {
    echo 1
}

SystemName_cheshire1() {
    echo "cheshire1"
}

SystemPowerOff_cheshire1() {
    RebootShutdown cheshire1
}

Arch_cheshire1() {
    echo "riscv"
}

ISA_cheshire1() {
    echo "rv64imafdcsuh"
}

SOC_cheshire1() {
    echo "PULP Platform Cheshire"
}

CPU_cheshire1() {
    echo "CVA6"
}

Cores_cheshire1() {
    echo "1"
}

RAM_cheshire1() {
    echo "1GB"
}

MaxCLK_cheshire1() {
    echo "50MHz"
}

Sel4Plat_cheshire1() {
    echo "cheshire"
}

PXELinux_cheshire1() {
    echo "no"
}

DTB_cheshire1() {
    echo "no"
}
