#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_haswell3() {
    echo 2
}

function SystemRunImage_haswell3() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" haswell3
    return $?
}

function SystemPowerOff_haswell3() {
    RebootShutdown haswell3
}

function Arch_haswell3() {
    echo "x86"
}

function ISA_haswell3() {
    echo "x86_64"
}

function SOC_haswell3() {
    echo "haswell"
}

function CPU_haswell3() {
    echo "?"
}

function Cores_haswell3() {
    echo "4(8)"
}

function RAM_haswell3() {
    echo "?"
}

function MaxCLK_haswell3() {
    echo "3.1Ghz"
}


