#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_haswell1() {
    echo 2
}

function SystemRunImage_haswell1() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    local rootserver=$6
    RebootConsoleRunTwoFiles "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" "${rootserver}" haswell1
    return $?
}

function SystemPowerOff_haswell1() {
    RebootShutdown haswell1
}

function Arch_haswell1() {
    echo "x86"
}

function ISA_haswell1() {
    echo "x86_64"
}

function SOC_haswell1() {
    echo "haswell"
}

function CPU_haswell1() {
    echo "E3-1220v3"
}

function Cores_haswell1() {
    echo "4(8)"
}

function RAM_haswell1() {
    echo "?"
}

function MaxCLK_haswell1() {
    echo "3.1Ghz"
}


