#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_haswell2() {
    echo 2
}

function SystemNotifyBamboo_haswell2() {
    curl --user admin:ertos -X POST -d 'JOB1&ExecuteAllStages' 'http://saison.keg.ertos.in.nicta.com.au:8085/rest/api/latest/queue/TOOLS-RUNQUEUEDHASWELL2JOBS'
}

function SystemRunImage_haswell2() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" haswell2
    return $?
}

function SystemPowerOff_haswell2() {
    RebootShutdown haswell2
}

function Arch_haswell2() {
    echo "x86"
}

function ISA_haswell2() {
    echo "x86_64"
}

function SOC_haswell2() {
    echo "haswell"
}

function CPU_haswell2() {
    echo "E3-1220v3"
}

function Cores_haswell2() {
    echo "4(8)"
}

function RAM_haswell2() {
    echo "?"
}

function MaxCLK_haswell2() {
    echo "3.1Ghz"
}


