#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_haswell4() {
    echo 2
}

SystemName_haswell4() {
    echo "haswell4"
}

SystemPowerOff_haswell4() {
    RebootShutdown haswell4
}

Arch_haswell4() {
    echo "x86"
}

ISA_haswell4() {
    echo "x86_64"
}

SOC_haswell4() {
    echo "haswell"
}

CPU_haswell4() {
    echo "i7-4770"
}

Cores_haswell4() {
    echo "4"
}

RAM_haswell4() {
    echo "16GB"
}

MaxCLK_haswell4() {
    echo "3.4Ghz"
}

Sel4Plat_haswell4() {
    echo "pc99:haswell"
}

PXELinux_haswell4() {
    echo "yes"
}

DTB_haswell4() {
    echo "no"
}
