#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_haswell3() {
    echo 2
}

SystemName_haswell3() {
    echo "haswell3"
}

SystemPowerOff_haswell3() {
    RebootShutdown haswell3
}

Arch_haswell3() {
    echo "x86"
}

ISA_haswell3() {
    echo "x86_64"
}

SOC_haswell3() {
    echo "haswell"
}

CPU_haswell3() {
    echo "?"
}

Cores_haswell3() {
    echo "4(8)"
}

RAM_haswell3() {
    echo "?"
}

MaxCLK_haswell3() {
    echo "3.1Ghz"
}

Sel4Plat_haswell3() {
    echo "pc99:haswell"
}
