#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_haswell4() {
    echo 2
}

function SystemRunImage_haswell4() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" haswell4
    return $?
}

function SystemPowerOff_haswell4() {
    RebootShutdown haswell4
}

function Arch_haswell4() {
    echo "x86"
}

function ISA_haswell4() {
    echo "x86_64"
}

function SOC_haswell4() {
    echo "haswell"
}

function CPU_haswell4() {
    echo "i7-4770"
}

function Cores_haswell4() {
    echo "4"
}

function RAM_haswell4() {
    echo "16GB"
}

function MaxCLK_haswell4() {
    echo "3.4Ghz"
}


