#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_haswell2() {
    echo 2
}

function SystemRunImage_haswell2() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" haswell2
    return $?
}

function SystemPowerOff_haswell2() {
    RebootShutdown haswell2
}

