#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_hifive1() {
    echo 1
}

SystemName_hifive1() {
    echo "hifive1"
}

SystemPowerOff_hifive1() {
    RebootShutdown hifive1
}

Arch_hifive1() {
    echo "riscv"
}

ISA_hifive1() {
    echo "riscv64"
}

SOC_hifive1() {
    echo "SiFive Freedom U540"
}

CPU_hifive1() {
    echo "U54-MC"
}

Cores_hifive1() {
    echo "4"
}

RAM_hifive1() {
    echo "2"
}

MaxCLK_hifive1() {
    echo "??"
}

Sel4Plat_hifive1() {
    echo "hifive"
}

PXELinux_hifive1() {
    echo "no"
}

DTB_hifive1() {
    echo "no"
}
