#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_hikey() {
    echo 1
}

function SystemRunImage_hikey() {
    local completion=$1
    local completion_timeout=$2
    local output=$3
    local kernel=$4
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${output}" "${kernel}" hikey
    return $?
}

function SystemPowerOff_hikey() {
    RebootShutdown hikey
}

function Arch_hikey() {
    echo "arm"
}

function ISA_hikey() {
    echo "armv8-a"
}

function SOC_hikey() {
    echo "kirin6220"
}

function CPU_hikey() {
    echo "cortex-a53"
}

function Cores_hikey() {
    echo "8"
}

function RAM_hikey() {
    echo "1GB"
}

function MaxCLK_hikey() {
    echo "1.2Ghz"
}
