#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_hikey() {
    echo 1
}

SystemName_hikey() {
    echo "hikey"
}

SystemPowerOff_hikey() {
    RebootShutdown hikey
}

Arch_hikey() {
    echo "arm"
}

ISA_hikey() {
    echo "armv8-a"
}

SOC_hikey() {
    echo "kirin6220"
}

CPU_hikey() {
    echo "cortex-a53"
}

Cores_hikey() {
    echo "8"
}

RAM_hikey() {
    echo "1GB"
}

MaxCLK_hikey() {
    echo "1.2Ghz"
}

Sel4Plat_hikey() {
    echo "hikey"
}

PXELinux_hikey() {
    echo "no"
}

DTB_hikey() {
    echo "no"
}
