#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_imx8mq() {
    echo 1
}

SystemName_imx8mq() {
    echo "imx8mq"
}

SystemPowerOff_imx8mq() {
    RebootShutdown imx8mq
}

Arch_imx8mq() {
    echo "arm"
}

ISA_imx8mq() {
    echo "armv8-a"
}

SOC_imx8mq() {
    echo "imx8m"
}

CPU_imx8mq() {
    echo "cortex-a53"
}

Cores_imx8mq() {
    echo "4"
}

RAM_imx8mq() {
    echo "3GB"
}

MaxCLK_imx8mq() {
    echo "1.4Ghz"
}

Sel4Plat_imx8mq() {
    echo "imx8mq-evk"
}
