#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_imx8mm() {
    if [ "$1" = '-L' ]
    then
	echo 2
    else
	echo 1
    fi
}

SystemName_imx8mm() {
    echo "imx8mm"
}

SystemPowerOff_imx8mm() {
    RebootShutdown imx8mm
}

Arch_imx8mm() {
    echo "arm"
}

ISA_imx8mm() {
    echo "armv8-a"
}

SOC_imx8mm() {
    echo "imx8mm"
}

CPU_imx8mm() {
    echo "cortex-a53"
}

Cores_imx8mm() {
    echo "4"
}

RAM_imx8mm() {
    echo "2GB"
}

MaxCLK_imx8mm() {
    echo "1.2Ghz"
}

Sel4Plat_imx8mm() {
    echo "imx8mm-evk"
}

PXELinux_imx8mm() {
    echo "yes"
}

DTB_imx8mm() {
    echo "yes"
}
