#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_inforce() {
    echo 1
}

function SystemRunImage_inforce() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" inforce
    return $?
}

function SystemPowerOff_inforce() {
    RebootShutdown inforce
}

