#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_inforce() {
    echo 1
}

function SystemNotifyBamboo_inforce() {
    curl --user admin:ertos -X POST -d 'JOB1&ExecuteAllStages' 'http://saison.keg.ertos.in.nicta.com.au:8085/rest/api/latest/queue/TOOLS-RUNQUEUEDINFORCEJOBS'
}

function SystemRunImage_inforce() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" inforce
    return $?
}

function SystemPowerOff_inforce() {
    RebootShutdown inforce
}

function Arch_inforce() {
    echo "arm"
}

function ISA_inforce() {
    echo "armv7-a"
}

function SOC_inforce() {
    echo "SnapdragonS4"
}

function CPU_inforce() {
    echo "Krait"
}

function Cores_inforce() {
    echo "4"
}

function RAM_inforce() {
    echo "2GB"
}

function MaxCLK_inforce() {
    echo "1.7Ghz"
}


