#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_inforce() {
    echo 1
}

function SystemRunImage_inforce() {
    local completion=$1
    local completion_timeout=$2
    local output=$3
    local kernel=$4
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${output}" "${kernel}" inforce
    return $?
}

function SystemPowerOff_inforce() {
    RebootShutdown inforce
}

function Arch_inforce() {
    echo "arm"
}

function ISA_inforce() {
    echo "armv7-a"
}

function SOC_inforce() {
    echo "SnapdragonS4"
}

function CPU_inforce() {
    echo "Krait"
}

function Cores_inforce() {
    echo "4"
}

function RAM_inforce() {
    echo "2GB"
}

function MaxCLK_inforce() {
    echo "1.7Ghz"
}


