#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_jetson() {
    echo 1
}

function SystemRunImage_jetson() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" jetson1
    return $?
}

function SystemPowerOff_jetson() {
    RebootShutdown jetson1
}

function Arch_jetson() {
    echo "arm"
}

function ISA_jetson() {
    echo "armv7-a"
}

function SOC_jetson() {
    echo "TegraK1"
}

function CPU_jetson() {
    echo "cortex-a15"
}

function Cores_jetson() {
echo "4(1)"
}

function RAM_jetson() {
    echo "2GB"
}

function MaxCLK_jetson() {
    echo "2.3Ghz"
}


