#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_jetson() {
    echo 1
}

function SystemRunImage_jetson() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" jetson1
    return $?
}

function SystemPowerOff_jetson() {
    RebootShutdown jetson1 
}

