#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_jetson2() {
    echo 1
}

function SystemName_jetson2() {
    echo "jetson2"
}

function SystemPowerOff_jetson2() {
    RebootShutdown jetson2
}

function Arch_jetson2() {
    echo "arm"
}

function ISA_jetson2() {
    echo "armv7-a"
}

function SOC_jetson2() {
    echo "TegraK1"
}

function CPU_jetson2() {
    echo "cortex-a15"
}

function Cores_jetson2() {
echo "4(1)"
}

function RAM_jetson2() {
    echo "2GB"
}

function MaxCLK_jetson2() {
    echo "2.3Ghz"
}

function Sel4Plat_jetson2() {
    echo "tk1"
}
