#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_kzm() {
    echo 1
}

function SystemRunImage_kzm() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" kzm11
    return $?
}

function SystemPowerOff_kzm() {
    RebootShutdown kzm
}

function Arch_kzm() {
    echo "arm"
}

function ISA_kzm() {
    echo "armv6"
}

function SOC_kzm() {
    echo "imx31"
}

function CPU_kzm() {
    echo "arm1136"
}

function Cores_kzm() {
    echo "1"
}

function RAM_kzm() {
    echo "128MB"
}

function MaxCLK_kzm() {
    echo "532Mhz"
}


