#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_odroid-xu4-1() {
    echo 1
}

function SystemName_odroid-xu4-1() {
    echo "odroid-xu4-1"
}

function SystemPowerOff_odroid-xu4-1() {
    RebootShutdown odroid-xu4-1
}

function Arch_odroid-xu4-1() {
    echo "arm"
}

function ISA_odroid-xu4-1() {
    echo "armv7-a"
}

function SOC_odroid-xu4-1() {
    echo "odroid-xu4-1"
}

function CPU_odroid-xu4-1() {
    echo "cortex-a15"
}

function Cores_odroid-xu4-1() {
    echo "4 (8)"
}

function RAM_odroid-xu4-1() {
    echo "2GB"
}

function MaxCLK_odroid-xu4-1() {
    echo "2GHz"
}

function Sel4Plat_odroid-xu4-1() {
    echo "exynos5:exynos5422"
}
