#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_odroidc2() {
    echo 1
}

function SystemName_odroidc2() {
    echo "odroidc2"
}

function SystemPowerOff_odroidc2() {
    RebootShutdown odroidc2
}

function Arch_odroidc2() {
    echo "arm"
}

function ISA_odroidc2() {
    echo "armv8-a"
}

function SOC_odroidc2() {
    echo "odroidc2"
}

function CPU_odroidc2() {
    echo "cortex-a53"
}

function Cores_odroidc2() {
    echo "4"
}

function RAM_odroidc2() {
    echo "2GB"
}

function MaxCLK_odroidc2() {
    echo "1.5GHz"
}
