#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_odroidxu() {
    echo 1
}

function SystemRunImage_odroidxu() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" odroid-xu
    return $?
}

function SystemPowerOff_odroidxu() {
    RebootShutdown odroid-xu
}

function Arch_odroidxu() {
    echo "arm"
}

function ISA_odroidxu() {
    echo "armv7-a"
}

function SOC_odroidxu() {
    echo "exynos5"
}

function CPU_odroidxu() {
    echo "cortex-a15(a7)"
}

function Cores_odroidxu() {
    echo "4(8)"
}

function RAM_odroidxu() {
    echo "2GB"
}

function MaxCLK_odroidxu() {
    echo "2Ghz"
}


