#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sabre() {
    echo 1
}

function SystemRunImage_sabre() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" sabre
    return $?
}

function SystemPowerOff_sabre() {
    RebootShutdown sabre
}

