#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sabre4() {
    echo 1
}

function SystemRunImage_sabre4() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" sabre4
    return $?
}

function SystemPowerOff_sabre4() {
    RebootShutdown sabre4
}

function Arch_sabre4() {
    echo "arm"
}

function ISA_sabre4() {
    echo "armv7-a"
}

function SOC_sabre4() {
    echo "imx6"
}

function CPU_sabre4() {
    echo "cortex-a9"
}

function Cores_sabre4() {
    echo "4"
}

function RAM_sabre4() {
    echo "1GB"
}

function MaxCLK_sabre4() {
    echo "1Ghz"
}


