#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_sabre() {
    echo 1
}

SystemName_sabre() {
    echo "sabre"
}

SystemPowerOff_sabre() {
    RebootShutdown sabre
}

Arch_sabre() {
    echo "arm"
}

ISA_sabre() {
    echo "armv7-a"
}

SOC_sabre() {
    echo "imx6"
}

CPU_sabre() {
    echo "cortex-a9"
}

Cores_sabre() {
    echo "4"
}

RAM_sabre() {
    echo "1GB"
}

MaxCLK_sabre() {
    echo "1Ghz"
}

Sel4Plat_sabre() {
    echo "imx6:sabre"
}
