#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sabre3() {
    echo 1
}

function SystemRunImage_sabre3() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" sabre3
    return $?
}

function SystemPowerOff_sabre3() {
    RebootShutdown sabre3
}

function Arch_sabre3() {
    echo "arm"
}

function ISA_sabre3() {
    echo "armv7-a"
}

function SOC_sabre3() {
    echo "imx6"
}

function CPU_sabre3() {
    echo "cortex-a9"
}

function Cores_sabre3() {
    echo "4"
}

function RAM_sabre3() {
    echo "1GB"
}

function MaxCLK_sabre3() {
    echo "1Ghz"
}


