#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sabre2() {
    echo 1
}

function SystemName_sabre2() {
    echo "sabre2"
}

function SystemPowerOff_sabre2() {
    RebootShutdown sabre2
}

function Arch_sabre2() {
    echo "arm"
}

function ISA_sabre2() {
    echo "armv7-a"
}

function SOC_sabre2() {
    echo "imx6"
}

function CPU_sabre2() {
    echo "cortex-a9"
}

function Cores_sabre2() {
    echo "4"
}

function RAM_sabre2() {
    echo "1GB"
}

function MaxCLK_sabre2() {
    echo "1Ghz"
}

function Sel4Plat_sabre2() {
    echo "imx6:sabre"
}
