#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sabre3() {
    echo 1
}

function SystemNotifyBamboo_sabre3() {
    curl --user admin:ertos -X POST -d 'JOB1&ExecuteAllStages' 'http://saison.keg.ertos.in.nicta.com.au:8085/rest/api/latest/queue/TOOLS-RUNQUEUEDSABRE3JOBS'
}

function SystemRunImage_sabre3() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" sabre3
    return $?
}

function SystemPowerOff_sabre3() {
    RebootShutdown sabre3
}

