#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_sabre4() {
    echo 1
}

SystemName_sabre4() {
    echo "sabre4"
}

SystemPowerOff_sabre4() {
    RebootShutdown sabre4
}

Arch_sabre4() {
    echo "arm"
}

ISA_sabre4() {
    echo "armv7-a"
}

SOC_sabre4() {
    echo "imx6"
}

CPU_sabre4() {
    echo "cortex-a9"
}

Cores_sabre4() {
    echo "4"
}

RAM_sabre4() {
    echo "1GB"
}

MaxCLK_sabre4() {
    echo "1Ghz"
}

Sel4Plat_sabre4() {
    echo "imx6:sabre"
}
