#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_sabre2() {
    echo 1
}

SystemName_sabre2() {
    echo "sabre2"
}

SystemPowerOff_sabre2() {
    RebootShutdown sabre2
}

Arch_sabre2() {
    echo "arm"
}

ISA_sabre2() {
    echo "armv7-a"
}

SOC_sabre2() {
    echo "imx6"
}

CPU_sabre2() {
    echo "cortex-a9"
}

Cores_sabre2() {
    echo "4"
}

RAM_sabre2() {
    echo "1GB"
}

MaxCLK_sabre2() {
    echo "1Ghz"
}

Sel4Plat_sabre2() {
    echo "imx6:sabre"
}
