#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_sandy() {
    echo 2
}

function SystemRunImage_sandy() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" sandy
    return $?
}

function SystemPowerOff_sandy() {
    RebootShutdown sandy
}

function Arch_sandy() {
    echo "x86"
}

function ISA_sandy() {
    echo "x86_64"
}

function SOC_sandy() {
    echo "sandybridge"
}

function CPU_sandy() {
    echo "i7-2600"
}

function Cores_sandy() {
    echo "4"
}

function RAM_sandy() {
    echo "?"
}

function MaxCLK_sandy() {
    echo "3.4Ghz"
}


