#!/bin/sh
#
# Copyright 2025 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_serengeti1() {
    echo 1
}

SystemName_serengeti1() {
    echo "serengeti1"
}

SystemPowerOff_serengeti1() {
    RebootShutdown serengeti1
}

Arch_serengeti1() {
    echo "riscv"
}

ISA_serengeti1() {
    echo "rv64imafdcsuh"
}

SOC_serengeti1() {
    echo "PULP Platform Cheshire"
}

CPU_serengeti1() {
    echo "CVA6"
}

Cores_serengeti1() {
    echo "1"
}

RAM_serengeti1() {
    echo "1GB"
}

MaxCLK_serengeti1() {
    echo "50MHz"
}

Sel4Plat_serengeti1() {
    echo "serengeti"
}

PXELinux_serengeti1() {
    echo "no"
}

DTB_serengeti1() {
    echo "no"
}
