#!/bin/sh
#
# Copyright 2025 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_serengeti2() {
    echo 1
}

SystemName_serengeti2() {
    echo "serengeti2"
}

SystemPowerOff_serengeti2() {
    RebootShutdown serengeti2
}

Arch_serengeti2() {
    echo "riscv"
}

ISA_serengeti2() {
    echo "rv64imafdcsuh"
}

SOC_serengeti2() {
    echo "PULP Platform Cheshire"
}

CPU_serengeti2() {
    echo "CVA6"
}

Cores_serengeti2() {
    echo "1"
}

RAM_serengeti2() {
    echo "1GB"
}

MaxCLK_serengeti2() {
    echo "50MHz"
}

Sel4Plat_serengeti2() {
    echo "serengeti"
}

PXELinux_serengeti2() {
    echo "no"
}

DTB_serengeti2() {
    echo "no"
}
