#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_skylake3() {
    echo 2
}

SystemName_skylake3() {
    echo "skylake3"
}

SystemPowerOff_skylake3() {
    RebootShutdown skylake3
}

Arch_skylake3() {
    echo "x86"
}

ISA_skylake3() {
    echo "x86_64"
}

SOC_skylake3() {
    echo "skylake3"
}

CPU_skylake3() {
    echo "i7-6700"
}

Cores_skylake3() {
    echo "4"
}

RAM_skylake3() {
    echo "8GB"
}

MaxCLK_skylake3() {
    echo "3.4Ghz"
}

Sel4Plat_skylake3() {
    echo "pc99:skylake"
}

PXELinux_skylake3() {
    echo "no"
}

DTB_skylake3() {
    echo "no"
}
