#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_skylake() {
    echo 2
}

function SystemRunImage_skylake() {
    local completion=$1
    local completion_timeout=$2
    local errortxt=$3
    local output=$4
    local kernel=$5
    local rootserver=$6
    RebootConsoleRunTwoFiles "${completion}" "${completion_timeout}" "${errortxt}" "${output}" "${kernel}" "${rootserver}" skylake
    return $?
}

function SystemPowerOff_skylake() {
    RebootShutdown skylake
}

function Arch_skylake() {
    echo "x86"
}

function ISA_skylake() {
    echo "x86_64"
}

function SOC_skylake() {
    echo "skylake"
}

function CPU_skylake() {
    echo "i7-6700"
}

function Cores_skylake() {
    echo "4"
}

function RAM_skylake() {
    echo "8GB"
}

function MaxCLK_skylake() {
    echo "3.4Ghz"
}


