#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_skylake2() {
    echo 2
}

SystemName_skylake2() {
    echo "skylake2"
}

SystemPowerOff_skylake2() {
    RebootShutdown skylake2
}

Arch_skylake2() {
    echo "x86"
}

ISA_skylake2() {
    echo "x86_64"
}

SOC_skylake2() {
    echo "skylake2"
}

CPU_skylake2() {
    echo "i7-6700"
}

Cores_skylake2() {
    echo "4"
}

RAM_skylake2() {
    echo "8GB"
}

MaxCLK_skylake2() {
    echo "3.4Ghz"
}

Sel4Plat_skylake2() {
    echo "pc99:skylake"
}
