#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_tardec2() {
    echo 2
}

SystemName_tardec2() {
    echo "tardec2"
}

SystemPowerOff_tardec2() {
    RebootShutdown tardec2
}

Arch_tardec2() {
    echo "x86"
}

ISA_tardec2() {
    echo "x86_64"
}

SOC_tardec2() {
    echo "?"
}

CPU_tardec2() {
    echo "i7-351UE"
}

Cores_tardec2() {
    echo "2"
}

RAM_tardec2() {
    echo "4GB"
}

MaxCLK_tardec2() {
    echo "1.7Ghz"
}

Sel4Plat_tardec2() {
    echo "pc99"
}

PXELinux_tardec2() {
    echo "no"
}

DTB_tardec2() {
    echo "no"
}
