#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_tardec1() {
    echo 2
}

function SystemRunImage_tardec1() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" tardec1
    return $?
}

function SystemPowerOff_tardec1() {
    RebootShutdown tardec1
}
