#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_tardec1() {
    echo 2
}

function SystemRunImage_tardec1() {
    local completion=$1
    local completion_timeout=$2
    local output=$3
    local kernel=$4
    local rootserver=$5
    RebootConsoleRunTwoFiles "${completion}" "${completion_timeout}" "${output}" "${kernel}" "${rootserver}" tardec1
    return $?
}

function SystemPowerOff_tardec1() {
    RebootShutdown tardec1
}

function Arch_tardec1() {
    echo "x86"
}

function ISA_tardec1() {
    echo "x86_64"
}

function SOC_tardec1() {
    echo "?"
}

function CPU_tardec1() {
    echo "i7-351UE"
}

function Cores_tardec1() {
    echo "2"
}

function RAM_tardec1() {
    echo "4GB"
}

function MaxCLK_tardec1() {
    echo "1.7Ghz"
}


