#!/bin/sh

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_tx2() {
    echo 1
}

SystemName_tx2() {
    echo "tx2"
}

SystemPowerOff_tx2() {
    RebootShutdown tx2
}

Arch_tx2() {
    echo "arm"
}

ISA_tx2() {
    echo "armv8-a"
}

SOC_tx2() {
    echo "TegraTX2"
}

CPU_tx2() {
    echo "cortex-a57"
}

Cores_tx2() {
    echo "4"
}

RAM_tx2() {
    echo "8GB"
}

MaxCLK_tx2() {
    echo "1.9Ghz"
}

Sel4Plat_tx2() {
    echo "tx2"
}
