#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_tx2a() {
    if [ "$1" = '-L' ]
    then
        echo 2
    else
        echo 1
    fi
}

SystemName_tx2a() {
    echo "tx2a"
}

SystemPowerOff_tx2a() {
    RebootShutdown tx2a
}

Arch_tx2a() {
    echo "arm"
}

ISA_tx2a() {
    echo "armv8-a"
}

SOC_tx2a() {
    echo "TegraTX2"
}

CPU_tx2a() {
    echo "cortex-a57"
}

Cores_tx2a() {
    echo "4"
}

RAM_tx2a() {
    echo "8GB"
}

MaxCLK_tx2a() {
    echo "1.9Ghz"
}

Sel4Plat_tx2a() {
    echo "tx2"
}
