#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_tx2b() {
    echo 1
}

SystemName_tx2b() {
    echo "tx2b"
}

SystemPowerOff_tx2b() {
    RebootShutdown tx2b
}

Arch_tx2b() {
    echo "arm"
}

ISA_tx2b() {
    echo "armv8-a"
}

SOC_tx2b() {
    echo "TegraTX2"
}

CPU_tx2b() {
    echo "cortex-a57"
}

Cores_tx2b() {
    echo "4"
}

RAM_tx2b() {
    echo "8GB"
}

MaxCLK_tx2b() {
    echo "1.9Ghz"
}

Sel4Plat_tx2b() {
    echo "tx2"
}

PXELinux_tx2b() {
    echo "no"
}

DTB_tx2b() {
    echo "no"
}
