#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_vtd() {
    echo 2
}

function SystemRunImage_vtd() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" vtd
    return $?
}

function SystemPowerOff_vtd() {
    RebootShutdown vtd
}

function SystemOutputDetails_vtd() {
    # "Arch\tISA\tCPU\tcores\tRAM\tClock\n"
        echo -e "x86\tx86_64\tCore 2\t???\t2\t???\t???"
}

