#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_vtd() {
    echo 2
}

function SystemNotifyBamboo_vtd() {
    curl --user admin:ertos -X POST -d 'JOB1&ExecuteAllStages' 'http://saison.keg.ertos.in.nicta.com.au:8085/rest/api/latest/queue/TOOLS-RUNQUEUEDVTDJOBS'
}

function SystemRunImage_vtd() {
    local completion=$1
    local output=$2
    local kernel=$3
    local rootserver=$4
    RebootConsoleRunTwoFiles "${completion}" "${output}" "${kernel}" "${rootserver}" vtd
    return $?
}

