#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_xavier_1() {
    echo 1
}

SystemName_xavier_1() {
    echo "xavier_1"
}

SystemPowerOff_xavier_1() {
    RebootShutdown xavier_1
}

Arch_xavier_1() {
    echo "arm"
}

ISA_xavier_1() {
    echo "armv8-a"
}

SOC_xavier_1() {
    echo "Xavier NX"
}

CPU_xavier_1() {
    echo "Nvidia Carmel"
}

Cores_xavier_1() {
    echo "6"
}

RAM_xavier_1() {
    echo "8GB"
}

MaxCLK_xavier_1() {
    echo "2.26Ghz"
}

Sel4Plat_xavier_1() {
    echo "xavier"
}

PXELinux_xavier_1() {
    echo "no"
}

DTB_xavier_1() {
    echo "no"
}
