#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_zc706() {
    echo 1
}

function SystemRunImage_zc706() {
    local completion=$1
    local completion_timeout=$2
    local output=$3
    local kernel=$4
    RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${output}" "${kernel}" zc706
    return $?
}

function SystemPowerOff_zc706() {
    RebootShutdown zc706
}

function Arch_zc706() {
    echo "arm"
}

function ISA_zc706() {
    echo "armv7-a"
}

function SOC_zc706() {
    echo "zynq-7000"
}

function CPU_zc706() {
    echo "cortex-a9"
}

function Cores_zc706() {
    echo "2"
}

function RAM_zc706() {
    echo "1GB"
}

function MaxCLK_zc706() {
    echo "800Mhz"
}


