#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function SystemNumFiles_zc706() {
    echo 1
}

function SystemRunImage_zc706() {
    local completion=$1
    local output=$2
    local kernel=$3
    RebootConsoleRunOneFile "${completion}" "${output}" "${kernel}" zc706
    return $?
}

function SystemPowerOff_zc706() {
    RebootShutdown zc706
}

