#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

SystemNumFiles_zcu102() {
    echo 1
}

SystemName_zcu102() {
    echo "zcu102"
}

SystemPowerOff_zcu102() {
    RebootShutdown zcu102
}

Arch_zcu102() {
    echo "arm"
}

ISA_zcu102() {
    echo "armv8-a"
}

SOC_zcu102() {
    echo "zcu102"
}

CPU_zcu102() {
    echo "cortex-a53"
}

Cores_zcu102() {
    echo "4"
}

RAM_zcu102() {
    echo "4GB"
}

MaxCLK_zcu102() {
    echo "??"
}

Sel4Plat_zcu102() {
    echo "zynqmp"
}

PXELinux_zcu102() {
    echo "no"
}

DTB_zcu102() {
    echo "no"
}
