#!/bin/bash
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

Systems_maaxboard_pool() {
    # This function can be explicit or programatic
    # Explicit:
    echo "maaxboard1"
    echo "maaxboard2"
}
