#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function Systems_sabre_pool() {
    # This function can be explicit or programatic

    for system in `SystemList`
    do
        if [ `SOC_${system}` == "imx6" ]; then
            echo ${system}
        fi
    done
    
    # Explicit:
    #echo "sabre"
    #echo "sabre2"
    #echo "sabre4"
}

function containsElement() {
    local e
    for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
    return 1
}


function GetRandomSystemFromPool_sabre_pool() {
    # Get a random system from the pool, unlocked if possible
    local sabre_systems=()
    local free_sabre_systems=()
    local locked_systems=()

    for lockedsys in `GetAllLockedSystems`; do 
        locked_systems+=(${lockedsys})
    done

    for system in `Systems_sabre_pool`
    do
        sabre_systems+=(${system})
        `containsElement "${system}" "${locked_systems[@]}"`
        if [ "$?" -ne 0 ]; then 
            free_sabre_systems+=(${system})
        fi
    done

    local RANDOM=$$$(date +%s)

    if [ "${#free_sabre_systems[@]}" == "0" ]; then
        # No free systems available, choosing random one
        echo ${sabre_systems[$RANDOM % ${#sabre_systems[@]} ]}
    else
        echo ${free_sabre_systems[$RANDOM % ${#free_sabre_systems[@]} ]}
    fi 
}

