#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

Systems_sabre_pool() {
    # This function can be explicit or programatic

    for system in $(SystemList)
    do
        if [ "$(SOC_${system})" = "imx6" ]; then
            echo ${system}
        fi
    done

    # Explicit:
    #echo "sabre"
    #echo "sabre2"
    #echo "sabre4"
}
