#!/bin/bash
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

Systems_x86_pool() {
    # This function can be explicit or programatic

    #for system in `SystemList`
    #do
    #    if [ `Arch_${system}` = "x86" ]; then
    #        echo ${system}
    #    fi
    #done

    # Explicit:
    echo "haswell3"
    echo "haswell4"
    echo "skylake"
    echo "skylake2"
#    echo "sandy"
}
