#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

# Define some global configuration variables and routines
BASE=/var/cache/machinelocks
HOST=tftp.keg.cse.unsw.edu.au

# Config file location
CONFIG=~/.mq

# Add all the other bits and pieces

. "${SCRIPT_PATH}/scripts/remote"
. "${SCRIPT_PATH}/scripts/lock"
. "${SCRIPT_PATH}/scripts/runner"
. "${SCRIPT_PATH}/scripts/system"
. "${SCRIPT_PATH}/scripts/pool"
. "${SCRIPT_PATH}/scripts/enqueue"

# Source the config file if it exists
if test -e $CONFIG; then
    source $CONFIG
fi

# Generate a random number between 1 and $1 inclusive
random()
{
    awk "
    BEGIN { srand();
    	  printf(\"%d\", $1 * rand() + 1);
    }"
}
