#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

# Define some global configuration variables and routines
BASE=/scratch/bamboo/machine_queue
HOST=saison

# Add all the other bits and pieces

. "${SCRIPT_PATH}/scripts/lock"
. "${SCRIPT_PATH}/scripts/system"
. "${SCRIPT_PATH}/scripts/queue"
. "${SCRIPT_PATH}/scripts/job"
. "${SCRIPT_PATH}/scripts/enqueue"
