#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

LOCKTIMEOUT=60
RUNQUEUELOCK="${BASE}/runqueue.lock"

# Remember in shell land that true and false are inverted, with 0 being true
have_queue_lock=1

function HaveLock() {
    return $have_queue_lock
}
function Lock() {
    if HaveLock; then
        echo "Already have lock! Scripts are fucked"
        exit -1
    fi
    lockfile -l "$LOCKTIMEOUT" "$RUNQUEUELOCK"
    if [ $? -eq 0 ]; then
        have_queue_lock=0
    fi
}
function Unlock() {
    if ! HaveLock; then
        echo "Do not have lock! Why are we releasing it? Scripts are fucked"
        exit -1
    else
        rm -f "$RUNQUEUELOCK"
    fi
    have_queue_lock=1
}
function EnsureLock() {
    if ! HaveLock; then
        echo "Cannot create job without lock!"
        exit -1
    fi
}
k
