#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ ! "${SCRIPT_PATH}" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

IsPoolValid() {
    pool=$1
    [ -f "${SCRIPT_PATH}/scripts/pools/${pool}" ]
}

PoolList() {
    (
	cd "${SCRIPT_PATH}/scripts/pools/" || exit
	echo * | sed 's/unavailable//'
    )
}

for pool in $(PoolList)
do
    . "${SCRIPT_PATH}/scripts/pools/${pool}"
done

OutputPoolList() {
    printf "+------------+-------------------------------------------------------------------------+\n"
    printf "| Name       | Systems                                                                 |\n"
    printf "+------------+-------------------------------------------------------------------------+\n"
    for pool in $(PoolList)
    do
        printf "| %10s " "${pool}"
        printf "| %-71s " "$("Systems_${pool}" | tr "\n" " ")"
        printf "|\n"
    done
    printf "+------------+-------------------------------------------------------------------------+\n"
}

OutputPoolTSV() {
    for pool in $(PoolList)
    do
        printf "%s" "${pool}"
        for system in $("Systems_${pool}")
        do
            printf "\t%s" "${system}"
        done
        printf "\n"
    done
}
