#!/bin/sh
#
# Copyright 2021 UNSW, Sydney
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

RemoteCommandOn() {
    host="$1"
    shift
    cmd="$@"
    ssh -tt -oLogLevel=quiet "${host}" "stty isig -onlcr -echoctl -echo ; $cmd"
    return $?
}

RemoteCommand() {
    if [ "$(hostname -f)" = "${HOST}" ]; then
	( # execute in a subshell so things like RemoteCommand exit
	  # don't teminate the shell.
            eval "$@"
	)
       return $?
    fi
    RemoteCommandOn "${HOST}" "$@"
}
