#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

RemoteCommandOn() {
    host="$1"
    shift
    cmd="$@"
    ssh -tt -oLogLevel=quiet "${host}" "stty isig -echoctl -echo ; $cmd"
    return $?
}

RemoteCommand() {
    if [ "$(hostname -f)" = "${HOST}" ]; then
	( # execute in a subshell so things like RemoteCommand exit
	  # don't teminate the shell.
            "$@"
	)
       return $?
    fi
    RemoteCommandOn "${HOST}" "$@"
}
