#!/bin/sh

if [ "${SCRIPT_PATH}" = "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

HaveRebootAndConsole() {
    HOSTS="
tftp
"
    echo "$HOSTS" | grep -q $(hostname)
}

RebootShutdown() {
    machine=$1
    if ! HaveRebootAndConsole; then
        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot --shutdown"
    else
        "/tftpboot/${machine}/reboot" --shutdown
    fi       
}

RebootConsoleRunTwoFiles() {
    [ "$1" = '-L' ] && {
	linux="-L"
	shift
    }
    [ "$1" = '-b' ] && {
        dtb="$2"
        dtbflag="$1 $2"
        shift
        shift
    }
    completion="$1"
    completion_timeout="$2"
    errortxt="$3"
    output="$4"
    keep_alive="$5"
    kernel="$6"
    rootserver="$7"
    machine="$8"

    if echo "$kernel" | grep -iq -v "kernel" && echo "$rootserver" | grep -iq "kernel"; then
        echo -e "\e[31mWARNING: Kernel image file must precede rootserver image file!\e[0m"
    fi

    ka_flag=""
    if $keep_alive ; then
        ka_flag="-a -i"
    fi

    if ! HaveRebootAndConsole; then
        logfile=$(RemoteCommandOn ${HOST} "mktemp")
        # need to copy remotely
        kernelfile=$(RemoteCommandOn ${HOST} "mktemp")
        rootserverfile=$(RemoteCommandOn ${HOST} "mktemp")
        dtbfile=$(RemoteCommandOn ${HOST} "mktemp")
        if ! scp "${kernel}" "${HOST}:${kernelfile}"; then
            echo "Failed to copy kernel image"
            RemoteCommandOn ${HOST} rm "${kernelfile}"
            RemoteCommandOn ${HOST} rm "${rootserverfile}"
            RemoteCommandOn ${HOST} rm "${logfile}"
            return 1
        fi
        if ! scp "${rootserver}" "${HOST}:${rootserverfile}"; then
            echo "Failed to copy rootserver image"
            RemoteCommandOn ${HOST} rm "${kernelfile}"
            RemoteCommandOn ${HOST} rm "${rootserverfile}"
            RemoteCommandOn ${HOST} rm "${logfile}"
            return 1
        fi
        if [ ! -z "${dtb}" ]; then
            if ! scp "${dtb}" "${HOST}:${dtbfile}"; then
                echo "Failed to copy dtb file"
                RemoteCommandOn ${HOST} rm "${kernelfile}"
                RemoteCommandOn ${HOST} rm "${rootserverfile}"
                RemoteCommandOn ${HOST} rm "${logfile}"
                RemoteCommandOn ${HOST} rm "${dtbfile}"
                return 1
            fi
        fi

        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' -u '${rootserverfile}' ${ka_flag}"
        ret=$?
        if [ "${output}" != "" ]; then
            scp "${HOST}:${logfile}" "${output}"
        fi
        RemoteCommandOn ${HOST} rm "${kernelfile}"
        RemoteCommandOn ${HOST} rm "${rootserverfile}"
        RemoteCommandOn ${HOST} rm "${logfile}"
        if [ ! -z "${dtb}" ]; then
            RemoteCommandOn ${HOST} rm "${dtbfile}"
        fi
        return $ret
    fi
    if [ "${output}" = "" ]; then
        "/tftpboot/${machine}/reboot"  $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
    else
        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
    fi
}

RebootConsoleRunOneFile() {
    [ "$1" = '-L' ] && {
	linux="-L"
	shift
    }
    [ "$1" = '-b' ] && {
    dtb="$2"
    dtbflag="$1 $2"
    shift
    shift
    }
    completion=$1
    completion_timeout=$2
    errortxt=$3
    output=$4
    keep_alive=$5
    kernel=$6
    machine=$7
    
    logfile=""
    kernelfile=""

    ka_flag=""
    if $keep_alive ; then
        ka_flag="-a -i"
    fi

    if ! HaveRebootAndConsole; then
        logfile=$(RemoteCommandOn ${HOST} "mktemp")
        # need to copy remotely
        kernelfile=$(RemoteCommandOn ${HOST} "mktemp")
        dtbfile=$(RemoteCommandOn ${HOST} "mktemp")
        if ! scp "${kernel}" "${HOST}:${kernelfile}"; then
            echo "Failed to copy kernel image"
            RemoteCommandOn ${HOST} rm "${kernelfile}"
            RemoteCommandOn ${HOST} rm "${logfile}"
            return 1
        fi
        if [ ! -z "${dtb}" ]; then
            if ! scp "${dtb}" "${HOST}:${kernelfile}"; then
                echo "Failed to copy dtb file"
                RemoteCommandOn ${HOST} rm "${dtbfile}"
                RemoteCommandOn ${HOST} rm "${kernelfile}"
                RemoteCommandOn ${HOST} rm "${logfile}"
            fi
        fi

        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux $dtbflag -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' ${ka_flag}"
        ret=$?
        if [ "${output}" != "" ]; then
            scp "${HOST}:${logfile}" "${output}"
        fi
        RemoteCommandOn ${HOST} rm "${kernelfile}"
        RemoteCommandOn ${HOST} rm "${logfile}"
        if [ ! -z "${dtb}" ]; then
            RemoteCommandOn ${HOST} rm "${dtbfile}"
        fi
        return $ret
    fi
    if [ "${output}" = "" ]; then
        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" ${ka_flag}
    else
        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" ${ka_flag}
    fi
}
