#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function IsSystemValid() {
    local system=$1
    if [ -e "${SCRIPT_PATH}/scripts/systems/${system}" ]; then
        return 0
    else
        return 1
    fi
}

function SystemList() {
    local system=""
    for system in `ls ${SCRIPT_PATH}/scripts/systems/`
    do
        if IsSystemValid; then
            echo "${system}"
        fi
    done
}

for system in `SystemList`
do
    . ${SCRIPT_PATH}/scripts/systems/${system}
done

function SystemCorrectNumberOfFiles() {
    local system=$1
    local num=$2
    local system_num=$(SystemNumFiles_${system})
    if [ "${num}" -eq "${system_num}" ]; then
        return 0
    else
        return 1
    fi
}

function SystemNotifyBamboo() {
    local system=$1
    SystemNotifyBamboo_${system}
}

function SystemRunImage() {
    local system=$1
    shift
    SystemRunImage_${system} "$@"
    return $?
}
