#!/bin/bash

if [ "${SCRIPT_PATH}" == "" ]; then
    echo "This script should not be called directly! Please use mq.sh"
    exit -1
fi

function IsSystemValid() {
    local system=$1
    [ -f "${SCRIPT_PATH}/scripts/systems/${system}" ]
}

function SystemList() {
    (
	cd "${SCRIPT_PATH}/scripts/systems/"
	echo * | sed 's/unavailable//'
    )
}

for system in $(SystemList)
do
    . "${SCRIPT_PATH}/scripts/systems/${system}"
done

function OutputSystemList() {
    local system=""
    printf "+----------------+------+---------+-----------------+----------------+-------+-------+--------+\n" 
    printf "| Name           | Arch | ISA     | SoC             | CPU            | Cores | RAM   | MaxCLK |\n"
    printf "+----------------+------+---------+-----------------+----------------+-------+-------+--------+\n"
    for system in $(SystemList)
    do
        printf "| %14s " "${system}"
        printf "| %4s "  "$("Arch_${system}")"
        printf "| %7s "  "$("ISA_${system}")"
        printf "| %15s " "$("SOC_${system}")"
        printf "| %14s " "$("CPU_${system}")"
        printf "| %5s "  "$("Cores_${system}")"
        printf "| %5s "  "$("RAM_${system}")"
        printf "| %6s "  "$("MaxCLK_${system}")"
        printf "|\n"
    done
    printf "+----------------+------+---------+-----------------+----------------+-------+-------+--------+\n"
    OutputPoolList
}

function OutputSystemTSV() {
    printf "name\tarch\tsel4_plat\tisa\tsoc\tcpu\tcores\tram\tmax_clk\tnum_files\n"
    for system in $(SystemList)
    do
		printf \
			"%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        	"${system}" \
        	"$("Arch_${system}")" \
        	"$("Sel4Plat_${system}")" \
        	"$("ISA_${system}")" \
        	"$("SOC_${system}")" \
        	"$("CPU_${system}")" \
        	"$("Cores_${system}")" \
        	"$("RAM_${system}")" \
        	"$("MaxCLK_${system}")" \
			"$("SystemNumFiles_${system}")"
    done
}

function SystemCorrectNumberOfFiles() {
    local system=$1
    local num=$2
    local system_num=""
    system_num="$("SystemNumFiles_${system}")"
    [ "${num}" -eq "${system_num}" ]
}

function SystemPowerOff() {
    local system=$1
    "SystemPowerOff_${system}"
}

function SystemRunImage() {
    local system=$1
    local completion=$2
    local completion_timeout=$3
    local errortxt=$4
    local logfile=$5
    local keep_alive=$6
    local kernel=$7
    local rootserver=""
    local system_name=""

    system_name="$("SystemName_${system}")"

    if [ "$("SystemNumFiles_${system}")" == "2" ]; then
        rootserver=$8
        RebootConsoleRunTwoFiles "${completion}" "${completion_timeout}" "${errortxt}" "${logfile}" "${keep_alive}" "${kernel}" "${rootserver}" "${system_name}"
    else
        RebootConsoleRunOneFile "${completion}" "${completion_timeout}" "${errortxt}" "${logfile}" "${keep_alive}" "${kernel}" "${system_name}"
    fi


}
